services:
  db:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: postgres_demo
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgresdbtest1
    volumes:
      - ./postgres:/var/lib/postgresql/data
